backend:
  name: github
  repo: JoaoTReis/landing-page-lenin
  base_url: https://www.lfadvocacia.net/
  auth_endpoint: api/auth/

media_folder: public/assets/img
public_folder: /assets/img

publish_mode: editorial_workflow

collections:
  - name: posts
    label: Artigos
    folder: posts
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Link do Artigo', name: 'link', widget: 'string' }
      - { label: 'Data de Publicação', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD hh:mm:ss' }
      - { label: 'Categoria', name: 'categoria', widget: 'select', options: ['direito civil', 'direito penal', 'direito trabalhista'] }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Conteúdo', name: 'body', widget: 'markdown' }
