backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "artigos"
    label: "Artigos"
    folder: "content/artigos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Descrição", name: "description", widget: "text" }
